type nul > file.AHK
type nul > file.APK
type nul > file.CSS
type nul > file.CSV
type nul > file.FLAC
type nul > file.GITIGNORE
type nul > file.HTML
type nul > file.INI
type nul > file.JAR
type nul > file.JS
type nul > file.JSON
type nul > file.LESS
type nul > file.MD
type nul > file.MP3
type nul > file.OGG
type nul > file.PDF
type nul > file.SCSS
type nul > file.SRT
type nul > file.TS
type nul > file.TXT
type nul > file.XML